name: CI

on:
  - workflow_dispatch
  - push

env:
  DENO_DIR: ~/deno_cache_dir

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ~/deno_cache_dir
          key: ${{ hashFiles('deno.lock') }}

      - name: Run Tests
        run: deno task test:ci

  lint:
    name: Lint
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x

      - name: Cache Deno dependencies
        uses: actions/cache@v4
        with:
          path: ~/deno_cache_dir
          key: ${{ hashFiles('deno.lock') }}

      - name: Lint
        run: deno lint
