name: Publish
on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v4

      - uses: denoland/setup-deno@v1.5.1
        with:
          deno-version: v2.0.0-rc.9

      - name: Publish package
        run: deno publish
